# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Codes\Python\ZPicture\core\front\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 717)
        self.mainWidget = QtWidgets.QWidget(MainWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainFrame = QtWidgets.QFrame(self.mainWidget)
        self.mainFrame.setStyleSheet("QFrame#mainFrame{\n"
"    border-radius:12px;\n"
"    background-color: qlineargradient(x1:0, y1:1, x2:1, y2:0, stop:0 rgba(101, 223, 201, 255), stop:1 rgba(108, 219, 235, 255));\n"
"}")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.body = QtWidgets.QFrame(self.mainFrame)
        self.body.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.content = QtWidgets.QFrame(self.body)
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout.addWidget(self.content)

        self.titleBar = QtWidgets.QFrame(self.body)
        self.titleBar.setMaximumSize(QtCore.QSize(36, 16777215))
        self.titleBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleBar.setObjectName("titleBar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.titleBar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")


        self.windowButton = QtWidgets.QFrame(self.titleBar)
        self.windowButton.setMinimumSize(QtCore.QSize(24, 0))
        self.windowButton.setMaximumSize(QtCore.QSize(24, 100))



        self.windowButton.setStyleSheet("\n"
"background-color:rgba(255, 255, 255,0);")
        self.windowButton.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.windowButton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.windowButton.setObjectName("windowButton")



        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.windowButton)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")


        self.shutDown = QtWidgets.QPushButton(self.windowButton)
        self.shutDown.setMinimumSize(QtCore.QSize(24, 24))
        self.shutDown.setMaximumSize(QtCore.QSize(24, 24))
        self.shutDown.setStyleSheet("border-radius:12px;\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:1, fy:0.5, stop:0 rgba(255, 255, 255,180), stop:1 rgba(255, 255, 255,75))")
        self.shutDown.setText("")

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/images/icon/shutDown.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shutDown.setIcon(icon)
        self.shutDown.setObjectName("shutDown")



        self.verticalLayout_4.addWidget(self.shutDown)


        self.maxAndNormal = QtWidgets.QPushButton(self.windowButton)
        self.maxAndNormal.setMinimumSize(QtCore.QSize(24, 24))
        self.maxAndNormal.setMaximumSize(QtCore.QSize(24, 24))
        self.maxAndNormal.setStyleSheet("border-radius:12px;\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:1, fy:0.5, stop:0 rgba(255, 255, 255,180), stop:1 rgba(255, 255, 255,75))")
        self.maxAndNormal.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/images/icon/max.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icon/images/icon/normal.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.maxAndNormal.setIcon(icon1)
        self.maxAndNormal.setCheckable(False)
        self.maxAndNormal.setObjectName("maxAndNormal")
        self.verticalLayout_4.addWidget(self.maxAndNormal)


        self.min = QtWidgets.QPushButton(self.windowButton)
        self.min.setMinimumSize(QtCore.QSize(24, 24))
        self.min.setMaximumSize(QtCore.QSize(24, 24))
        self.min.setStyleSheet("border-radius:12px;\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:1, fy:0.5, stop:0 rgba(255, 255, 255,180), stop:1 rgba(255, 255, 255,75))")
        self.min.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/images/icon/min.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min.setIcon(icon2)
        self.min.setObjectName("min")
        self.verticalLayout_4.addWidget(self.min)

        self.verticalLayout_3.addWidget(self.windowButton, 0, QtCore.Qt.AlignHCenter)

        self.iconAndTitle = QtWidgets.QFrame(self.titleBar)
        self.iconAndTitle.setMinimumSize(QtCore.QSize(36, 0))
        self.iconAndTitle.setMaximumSize(QtCore.QSize(36, 16777215))
        self.iconAndTitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.iconAndTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.iconAndTitle.setObjectName("iconAndTitle")


        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.iconAndTitle)
        self.verticalLayout_5.setContentsMargins(0, 20, 0, 20)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.titleIcon = QtWidgets.QFrame(self.iconAndTitle)

        self.titleIcon.setMinimumSize(QtCore.QSize(30, 30))
        self.titleIcon.setMaximumSize(QtCore.QSize(30, 30))
        self.titleIcon.setStyleSheet("image: url(:/icon/images/icon/Z.svg);")
        self.titleIcon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleIcon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleIcon.setObjectName("titleIcon")
        self.verticalLayout_5.addWidget(self.titleIcon)
        self.verticalLayout_3.addWidget(self.iconAndTitle, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.titleBar)
        self.verticalLayout_2.addWidget(self.body)
        self.statusBar = QtWidgets.QFrame(self.mainFrame)
        self.statusBar.setMaximumSize(QtCore.QSize(16777215, 24))
        self.statusBar.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.statusBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statusBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusBar.setObjectName("statusBar")
        self.verticalLayout_2.addWidget(self.statusBar)
        self.verticalLayout.addWidget(self.mainFrame)
        MainWindow.setCentralWidget(self.mainWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)

    window = Ui_MainWindow()
